### PR TITLE
Filter by category #58

### PR DESCRIPTION
**Pull request by KagisoLegodi**
Added api route to fetch all the categories and also ran test to see if the categories are being successfully fetched . The test is successfull . 

https://github.com/user-attachments/assets/db897cbb-8093-4041-9fde-83239f338bd6

### CODE REVIEW

**Review by HloleloRampete — DISMISSED** [review]
The code test is also Successful from my end.

**Review by IkanyengAdams — APPROVED** [review]
this pull request, creates a API endpoint for all categories,

**Review by IkanyengAdams — APPROVED** [review]
This pull request creates an endpoint for categories

**Review by NeoPhetoane — COMMENTED** [review]
Categories endpoint functions effectively and was tested.
Dependencies updated to accommodate tailwind merge

**Pull request merged**
