### PR TITLE
Dummy data

### PR DESCRIPTION
**Pull request by ElzabeEls**

### CODE REVIEW

**Review by Moosa-24 — DISMISSED** [review]

**Review by OmphileMorwane — DISMISSED** [review]
The changes collectively integrate Storybook with the project, set up linting improvements, and introduce components with corresponding stories for UI documentation

**Review by Moosa-24 — DISMISSED** [review]
The updated code integrates Storybook with the project, it also sets up linting improvements, and introduces new components with corresponding stories for UI documentation

**Review by OmphileMorwane — APPROVED** [review]
Selected incoming changes and resolved conflicts

**Review by KagisoLegodi — APPROVED** [review]
al checks passed

**Review by Moosa-24 — APPROVED** [review]
all issues have been dealt with accordingly

N.B. framer-motion@11.11.9 was also installed

**Pull request merged**
