### PR TITLE
Install mongo db driver #65

### PR DESCRIPTION
**Pull request by KagisoLegodi**
I installed latest mongoDB dependency and  upgraded the folder structure

### CODE REVIEW

**Review by Mokawane — COMMENTED** [review]
Everything is looking okay from my side.

**Review by Mokawane — APPROVED** [review]
Everything is looking okay from my side.

**Review by OmphileMorwane — APPROVED** [review]
Review completed!

**Comment by OmphileMorwane** [comment]
Review done.

**Comment by OmphileMorwane** [comment]
Review completed

**Comment by OmphileMorwane** [comment]
Successfully merged.

**Pull request merged**
